DWKRFUID ;PICASSO/JOLLIS - UUID ROUTINES;9/11/10;src/krnl/KRNLFUID.m
;;3.0;KERNEL;9/11/2010;1
;; $Id: DWKRFUID.m 4 2010-10-24 17:30:25Z jollis $

;;PDOC
;;SUMMARY Get the next FUID in the sequence
;;DEFFCN
GETNEXT()
;;PDOC/	
 TS
 S ^DWPREF("UIDMAX")=^DWPREF("UIDMAX")+1
 S TU=^DWPREF("SITENAME")_^DWPREF("UIDMAX")
 TC
 Q TU