UNIVERSE

RECPOINT(DATA,TIME)
 S ^DWUNIVRS(DATA,TIME)=DATA
 S ^DWUNIVRS(DATA,TIME,"MAXLIMIT")=0
 Q

ADDLIMIT(DATA,LIMIT,TIME)
 SET ^DWUNIVRS(DATA,TIME,"MAXLIMIT")=^DWUNIVRS(DATA,TIME,"MAXLIMIT")+1
 SET ^DWUNIVRS(DATA,TIME,"LIMITS",^DWUNIVRS(DATA,TIME,"MAXLIMIT"))=LIMIT
 FOR CURLIMIT=0:1:^DWUNIVRS(DATA,TIME,"MAXLIMIT") DO
 . SET CURRENTDATANODE = ^DWUNIVRS(DATA,TIME)
 . SET CURRENTGLOBALROOT = "^DWUNIVRS("_""_DATA_"",""_TIME_""_")"
 . XECUTE ^DWUNIVRS(DATA,TIME,CURLIMIT)

;; NOTE: THE FUNCTION PASSED TO "LIMIT" MUST SET THE 
;;       VALUE AT CURRENTGLOBALROOT TO THE VALUE OF 
;;       LIMIT of DATA at TIME
