HOOKTEST

ROOTUPDT(EVTYPE,UID,KEY,REVN,DATA)
 W !!,"HOOK RUN: EVTYPE=",EVTYPE," UID=",UID," KEY=",KEY," REV=",REVN
 W " DATA=",DATA,!!
 TS
 S ^HOOKRUN(1)="ROOTUPDT"
 TC
 Q

ROOTUPD1(EVTYPE,UID,KEY,REVN,DATA)
 W !!,"HOOK RUN: EVTYPE=",EVTYPE," UID=",UID," KEY=",KEY," REV=",REVN
 W " DATA=",DATA,!!
 TS
 S ^HOOKRUN(2)="ROOTUPD1"
 TC
 Q